#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ecosystem Integration Hooks v2.0 — Round 9 Expansion
===========================================================================
Conecta bibliotecas recomendadas pelo PyPI Scout aos pipelines do ecossistema:
  SEEKER → MASWOS → PhD_Auditor → data_analysis → MCP_server
  + Geo → Finance → Crypto → BioMed → Qualis A1 (Round 9)

Auto-generated by: /evolve pipeline (Rounds 8 & 9)
Parent skill: pypi-scout v1.0.0
Total hooks: 10 | Domínios: 8
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger("EcosystemHooks")

# ─────────────────────────────────────────────────────────────────────
# HOOK 1: SEEKER — Busca bibliográfica multi-fonte
# ─────────────────────────────────────────────────────────────────────


@dataclass
class PaperResult:
    """Resultado unificado de busca de artigo acadêmico."""
    title: str
    authors: list[str] = field(default_factory=list)
    year: int | None = None
    doi: str = ""
    citations: int = 0
    source: str = ""  # "arxiv", "semanticscholar", "scholarly", "crossref"
    abstract: str = ""
    url: str = ""
    pdf_url: str | None = None


class SeekerMultiSource:
    """Busca acadêmica multi-fonte usando bibliotecas do PyPI Scout.
    
    Afinidade: scholarly(95%), arxiv(95%), semanticscholar(95%), scihub-cn(95%)
    """

    @staticmethod
    def search_arxiv(query: str, max_results: int = 10) -> list[PaperResult]:
        """Busca no arXiv."""
        try:
            import arxiv
            client = arxiv.Client()
            search = arxiv.Search(
                query=query,
                max_results=max_results,
                sort_by=arxiv.SortCriterion.Relevance,
            )
            results = []
            for r in client.results(search):
                results.append(PaperResult(
                    title=r.title,
                    authors=[str(a) for a in r.authors],
                    year=r.published.year if r.published else None,
                    doi=getattr(r, 'doi', ''),
                    source="arxiv",
                    abstract=r.summary,
                    url=r.entry_id,
                    pdf_url=r.pdf_url,
                ))
            logger.info(f"arXiv: {len(results)} resultados para '{query}'")
            return results
        except ImportError:
            logger.warning("arxiv não instalado. Use: pip install arxiv")
            return []
        except Exception as e:
            logger.error(f"Erro arXiv: {e}")
            return []

    @staticmethod
    def search_semanticscholar(query: str, limit: int = 10) -> list[PaperResult]:
        """Busca no Semantic Scholar."""
        try:
            from semanticscholar import SemanticScholar
            sch = SemanticScholar(timeout=30)
            raw = sch.search_paper(query, limit=limit)
            results = []
            for r in raw:
                results.append(PaperResult(
                    title=getattr(r, 'title', ''),
                    authors=[str(a.get('name', '')) for a in getattr(r, 'authors', [])],
                    year=getattr(r, 'year', None),
                    doi=getattr(r, 'externalIds', {}).get('DOI', ''),
                    citations=getattr(r, 'citationCount', 0),
                    source="semanticscholar",
                    abstract=getattr(r, 'abstract', ''),
                    url=getattr(r, 'url', ''),
                ))
            logger.info(f"Semantic Scholar: {len(results)} resultados para '{query}'")
            return results
        except ImportError:
            logger.warning("semanticscholar não instalado. Use: pip install semanticscholar")
            return []
        except Exception as e:
            logger.error(f"Erro Semantic Scholar: {e}")
            return []

    @staticmethod
    def search_scholarly(query: str, max_results: int = 5) -> list[PaperResult]:
        """Busca no Google Scholar via scholarly."""
        try:
            from scholarly import scholarly, ProxyGenerator
            pg = ProxyGenerator()
            try:
                pg.FreeProxies()
                scholarly.use_proxy(pg)
            except Exception:
                pass  # Sem proxy, tenta direto
            
            search = scholarly.search_pubs(query)
            results = []
            for i, r in enumerate(search):
                if i >= max_results:
                    break
                bib = r.get('bib', {})
                results.append(PaperResult(
                    title=bib.get('title', ''),
                    authors=[bib.get('author', '')],
                    year=int(bib.get('pub_year', 0)) if bib.get('pub_year') else None,
                    source="scholarly",
                    abstract=bib.get('abstract', ''),
                    url=r.get('pub_url', ''),
                    citations=r.get('num_citations', 0),
                ))
            logger.info(f"Google Scholar: {len(results)} resultados para '{query}'")
            return results
        except ImportError:
            logger.warning("scholarly não instalado. Use: pip install scholarly")
            return []
        except Exception as e:
            logger.error(f"Erro scholarly: {e}")
            return []

    @staticmethod
    def search_all(query: str, max_per_source: int = 5) -> dict[str, list[PaperResult]]:
        """Busca em todas as fontes simultaneamente."""
        return {
            "arxiv": SeekerMultiSource.search_arxiv(query, max_per_source),
            "semanticscholar": SeekerMultiSource.search_semanticscholar(query, max_per_source),
            "scholarly": SeekerMultiSource.search_scholarly(query, max_per_source),
        }


# ─────────────────────────────────────────────────────────────────────
# HOOK 2: World Bank Data → PhD Auditor
# ─────────────────────────────────────────────────────────────────────


class WorldBankAnalyzer:
    """Análise de dados do Banco Mundial para PhD Auditor.
    
    Afinidade: wbgapi(95%), data_analysis(95%)
    """

    @staticmethod
    def get_indicator_data(
        indicator: str,
        country: str = "BRA",
        years: range | None = None,
    ) -> dict[str, Any]:
        """Obtém dados de um indicador do World Bank.
        
        Args:
            indicator: Código do indicador (ex: 'NY.GDP.PCAP.CD' para PIB per capita)
            country: Código ISO do país (default: 'BRA')
            years: Range de anos (default: 2010-2024)
        
        Returns:
            Dict com valores anuais e metadados
        """
        if years is None:
            years = range(2010, 2025)
        
        try:
            import wbgapi as wb
            data: Any = wb.data.fetch(indicator, country, list(years))  # type: ignore[arg-type]
            series_info = wb.series.get(indicator)
            return {
                "indicator": indicator,
                "name": series_info.get("value", indicator) if series_info else indicator,  # type: ignore[union-attr]
                "country": country,
                "values": str(data),
                "source": "World Bank (wbgapi)",
            }
        except ImportError:
            logger.warning("wbgapi não instalado. Use: pip install wbgapi")
            return {"error": "wbgapi not installed"}
        except Exception as e:
            logger.error(f"Erro WBGAPI: {e}")
            return {"error": str(e)}

    @staticmethod
    def compare_countries(
        indicator: str,
        countries: list[str],
        year: int = 2023,
    ) -> dict[str, float]:
        """Compara indicador entre países."""
        try:
            import wbgapi as wb
            data: Any = wb.data.fetch(indicator, countries, [year])  # type: ignore[arg-type]
            return dict(data) if data else {}
        except ImportError:
            return {}
        except Exception:
            return {}

    @staticmethod
    def list_indicators(keyword: str = "", limit: int = 20) -> list[dict[str, str]]:
        """Lista indicadores disponíveis por palavra-chave."""
        try:
            import wbgapi as wb
            results = []
            for s in wb.series.list():
                name = s.get("value", "")
                if keyword.lower() in name.lower():
                    results.append({
                        "id": s.get("id", ""),
                        "name": name,
                        "source": s.get("source", {}).get("value", ""),
                    })
                    if len(results) >= limit:
                        break
            return results
        except ImportError:
            return []


# ─────────────────────────────────────────────────────────────────────
# HOOK 3: PDF Processing → MASWOS
# ─────────────────────────────────────────────────────────────────────


class PDFProcessor:
    """Processamento de PDFs para o pipeline MASWOS.
    
    Afinidade: pypdf(90%)
    """

    @staticmethod
    def extract_text(pdf_path: Path) -> str:
        """Extrai texto de um PDF."""
        try:
            from pypdf import PdfReader
            reader = PdfReader(str(pdf_path))
            text = ""
            for page in reader.pages:
                text += page.extract_text() or ""
            logger.info(f"PDF: {len(reader.pages)} páginas, {len(text)} caracteres")
            return text
        except ImportError:
            logger.warning("pypdf não instalado. Use: pip install pypdf")
            return ""
        except Exception as e:
            logger.error(f"Erro pypdf: {e}")
            return ""

    @staticmethod
    def get_metadata(pdf_path: Path) -> dict[str, Any]:
        """Extrai metadados de um PDF."""
        try:
            from pypdf import PdfReader
            reader = PdfReader(str(pdf_path))
            return {
                "pages": len(reader.pages),
                "metadata": dict(reader.metadata) if reader.metadata else {},
            }
        except ImportError:
            return {}
        except Exception:
            return {}


# ─────────────────────────────────────────────────────────────────────
# HOOK 4: MCP Integration
# ─────────────────────────────────────────────────────────────────────


class MCPScoutBridge:
    """Ponte entre PyPI Scout e servidores MCP.
    
    Afinidade: mcp(100%)
    """

    @staticmethod
    def discover_mcp_packages() -> list[dict[str, str]]:
        """Descobre pacotes MCP disponíveis no PyPI via catálogo."""
        catalog_path = Path(__file__).parent / "opencode_catalog.json"
        if not catalog_path.exists():
            return []
        
        with open(catalog_path, encoding="utf-8") as f:
            catalog = json.load(f)
        
        mcp_pkgs = catalog.get("categories", {}).get("mcp_ecosystem", {}).get("packages", [])
        return [
            {"name": p["name"], "install": p.get("install", ""), "description": p.get("description", "")}
            for p in mcp_pkgs
        ]

    @staticmethod
    def list_installed_mcp() -> list[str]:
        """Lista pacotes MCP já instalados."""
        import importlib
        mcp_packages = ["mcp", "fastmcp", "openai-agents-mcp", "langchain-mcp-adapters"]
        installed = []
        for pkg in mcp_packages:
            try:
                importlib.import_module(pkg)
                installed.append(pkg)
            except ImportError:
                pass
        return installed


# ─────────────────────────────────────────────────────────────────────
# HOOK 5: HTTPX Client → OpenCode Core
# ─────────────────────────────────────────────────────────────────────


class HTTPXClient:
    """Cliente HTTP assíncrono para o ecossistema.
    
    Afinidade: httpx(88%)
    """
    
    @staticmethod
    async def fetch_json_async(url: str, timeout: float = 30.0) -> dict[str, Any]:
        """Fetch JSON assíncrono."""
        try:
            import httpx
            async with httpx.AsyncClient(timeout=timeout) as client:
                resp = await client.get(url)
                resp.raise_for_status()
                return resp.json()
        except ImportError:
            return {"error": "httpx not installed"}
        except Exception as e:
            return {"error": str(e)}
    
    @staticmethod
    def fetch_json_sync(url: str, timeout: float = 30.0) -> dict[str, Any]:
        """Fetch JSON síncrono."""
        try:
            import httpx
            resp = httpx.get(url, timeout=timeout)
            resp.raise_for_status()
            return resp.json()
        except ImportError:
            return {"error": "httpx not installed"}
        except Exception as e:
            return {"error": str(e)}


# ─────────────────────────────────────────────────────────────────────
# HOOK 6: GeoAnalyzer — Dados Geográficos (Round 9)
# ─────────────────────────────────────────────────────────────────────


class GeoAnalyzer:
    """Análise geoespacial com GeoPandas + Folium.
    
    Afinidade: geopandas(95%), folium(90%)
    Já instalado no ecossistema (geopandas v1.1.3).
    """

    @staticmethod
    def load_brazil_states() -> Any:
        """Carrega shapefile dos estados brasileiros."""
        try:
            import geopandas as gpd
            url = "https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson"
            return gpd.read_file(url)
        except ImportError:
            return None
        except Exception as e:
            logger.error(f"GeoAnalyzer: {e}")
            return None

    @staticmethod
    def geocode(address: str) -> dict[str, float] | None:
        """Geocodifica um endereço para coordenadas."""
        try:
            from geopy.geocoders import Nominatim
            geolocator = Nominatim(user_agent="opencode_ecosystem")
            location = geolocator.geocode(address, timeout=10)
            if location:
                return {"lat": location.latitude, "lon": location.longitude, "address": location.address}
        except ImportError:
            pass
        except Exception as e:
            logger.error(f"Geocode: {e}")
        return None

    @staticmethod
    def create_map(points: list[dict[str, Any]], center: tuple[float, float] = (-15.78, -47.93)) -> Any:
        """Cria mapa interativo com Folium."""
        try:
            import folium
            m = folium.Map(location=center, zoom_start=4)
            for pt in points:
                folium.Marker(
                    [pt.get("lat", 0), pt.get("lon", 0)],
                    popup=pt.get("name", ""),
                ).add_to(m)
            return m
        except ImportError:
            return None


# ─────────────────────────────────────────────────────────────────────
# HOOK 7: FinanceAnalyzer — Yahoo Finance + FRED (Round 9)
# ─────────────────────────────────────────────────────────────────────


class FinanceAnalyzer:
    """Dados financeiros: Yahoo Finance + FRED + Market Calendars.
    
    Afinidade: yfinance(95%), fredapi(90%)
    """

    @staticmethod
    def get_stock_data(ticker: str, period: str = "1y") -> dict[str, Any]:
        """Obtém dados de ação via Yahoo Finance."""
        try:
            import yfinance as yf
            stock = yf.Ticker(ticker)
            info = stock.info
            hist = stock.history(period=period)
            return {
                "ticker": ticker,
                "name": info.get("longName", ticker),
                "sector": info.get("sector", ""),
                "market_cap": info.get("marketCap", 0),
                "current_price": info.get("currentPrice", 0),
                "pe_ratio": info.get("trailingPE", None),
                "dividend_yield": info.get("dividendYield", None),
                "history_rows": len(hist),
                "history_latest": hist.tail(5).to_dict() if not hist.empty else {},
            }
        except ImportError:
            return {"error": "yfinance not installed"}
        except Exception as e:
            return {"error": str(e)[:100]}

    @staticmethod
    def get_fred_series(series_id: str, api_key: str = "") -> Any:
        """Obtém série temporal do FRED (Federal Reserve).
        
        Precisa de API key gratuita: https://fred.stlouisfed.org/docs/api/api_key.html
        """
        try:
            from fredapi import Fred
            fred = Fred(api_key=api_key)
            return fred.get_series(series_id)
        except ImportError:
            return None
        except Exception as e:
            logger.error(f"FRED: {e}")
            return None

    @staticmethod
    def get_market_calendar(exchange: str = "NYSE", start: str = "2024-01-01", end: str = "2024-12-31") -> Any:
        """Obtém calendário de pregão."""
        try:
            import pandas_market_calendars as mcal
            cal = mcal.get_calendar(exchange)
            return cal.schedule(start_date=start, end_date=end)
        except ImportError:
            return None

    @staticmethod
    def compare_stocks(tickers: list[str]) -> dict[str, dict[str, Any]]:
        """Compara múltiplas ações."""
        results = {}
        for t in tickers:
            results[t] = FinanceAnalyzer.get_stock_data(t)
        return results


# ─────────────────────────────────────────────────────────────────────
# HOOK 8: MarketSpeculator — Cripto + Derivativos (Round 9)
# ─────────────────────────────────────────────────────────────────────


class MarketSpeculator:
    """Mercado especulativo: CCXT (110+ exchanges cripto).
    
    Afinidade: ccxt(95%)
    """

    @staticmethod
    def get_exchanges() -> list[str]:
        """Lista exchanges disponíveis."""
        try:
            import ccxt
            return ccxt.exchanges[:20]
        except ImportError:
            return []

    @staticmethod
    def get_ticker(exchange_id: str, symbol: str) -> dict[str, Any]:
        """Obtém ticker de uma exchange cripto."""
        try:
            import ccxt
            exchange_class = getattr(ccxt, exchange_id)
            exchange = exchange_class({"enableRateLimit": True})
            ticker = exchange.fetch_ticker(symbol)
            return {
                "exchange": exchange_id,
                "symbol": symbol,
                "last": ticker.get("last", 0),
                "bid": ticker.get("bid", 0),
                "ask": ticker.get("ask", 0),
                "volume": ticker.get("baseVolume", 0),
                "change_24h": ticker.get("percentage", 0),
            }
        except ImportError:
            return {"error": "ccxt not installed"}
        except Exception as e:
            return {"error": str(e)[:100]}

    @staticmethod
    def get_top_crypto(n: int = 5) -> list[dict[str, Any]]:
        """Top criptomoedas por volume (Binance)."""
        return MarketSpeculator._fetch_top_from_exchange("binance", n)

    @staticmethod
    def _fetch_top_from_exchange(exchange_id: str, n: int) -> list[dict[str, Any]]:
        try:
            import ccxt
            exchange = getattr(ccxt, exchange_id)({"enableRateLimit": True})
            markets = exchange.fetch_tickers()
            # Filtrar USDT pairs e ordenar por volume
            usdt_pairs = {
                k: v for k, v in markets.items()
                if k.endswith("/USDT") and v.get("quoteVolume", 0) > 0
            }
            sorted_pairs = sorted(
                usdt_pairs.items(),
                key=lambda x: x[1].get("quoteVolume", 0),
                reverse=True,
            )[:n]
            return [
                {
                    "symbol": k,
                    "price": v.get("last", 0),
                    "volume_24h": v.get("quoteVolume", 0),
                    "change_24h": v.get("percentage", 0),
                }
                for k, v in sorted_pairs
            ]
        except Exception as e:
            logger.error(f"Crypto fetch: {e}")
            return []


# ─────────────────────────────────────────────────────────────────────
# HOOK 9: BioMedAnalyzer — Biologia + Saúde (Round 9)
# ─────────────────────────────────────────────────────────────────────


class BioMedAnalyzer:
    """Análise biomédica: BioPython + PySUS (DATASUS).
    
    Afinidade: biopython(85%), pysus(90%)
    """

    @staticmethod
    def search_pubmed(query: str, max_results: int = 5) -> list[dict[str, Any]]:
        """Busca artigos no PubMed/NCBI via BioPython."""
        try:
            from Bio import Entrez
            Entrez.email = "opencode@ecosystem.br"
            handle = Entrez.esearch(db="pubmed", term=query, retmax=max_results)
            record = Entrez.read(handle)
            handle.close()

            ids = record.get("IdList", [])
            if not ids:
                return []

            handle = Entrez.efetch(db="pubmed", id=",".join(ids), rettype="xml", retmode="text")
            records = Entrez.read(handle)
            handle.close()

            results = []
            for article in records.get("PubmedArticle", []):
                medline = article.get("MedlineCitation", {}).get("Article", {})
                title = medline.get("ArticleTitle", "")
                authors_list = medline.get("AuthorList", [])
                authors = [
                    f"{a.get('LastName', '')} {a.get('ForeName', '')}"
                    for a in authors_list[:3]
                ]
                results.append({
                    "title": str(title),
                    "authors": authors,
                    "pmid": str(article.get("MedlineCitation", {}).get("PMID", "")),
                    "source": "PubMed/NCBI",
                })
            logger.info(f"PubMed: {len(results)} results for '{query}'")
            return results
        except ImportError:
            logger.warning("biopython not installed")
            return []
        except Exception as e:
            logger.error(f"PubMed: {e}")
            return []

    @staticmethod
    def get_datasus_data(dataset: str = "sinan") -> dict[str, Any]:
        """Acessa dados do DATASUS (saúde pública brasileira) via PySUS.
        
        Datasets disponíveis: sinan, sim, sinasc, sih, etc.
        """
        try:
            import pysus
            return {
                "dataset": dataset,
                "source": "DATASUS (PySUS)",
                "description": f"Dados de {dataset.upper()} — Sistema de Informação do SUS",
                "note": "PySUS v2.1.0 requer configuração de conexão FTP",
            }
        except ImportError:
            return {"error": "pysus not installed. Use: pip install pysus"}
        except Exception as e:
            return {"error": str(e)[:100]}

    @staticmethod
    def get_covid_stats() -> dict[str, Any]:
        """Estatísticas COVID-19 via Johns Hopkins + Worldometers."""
        try:
            from covid import Covid
            covid = Covid(source="worldometers")
            brazil = covid.get_status_by_country_name("brazil")
            return {
                "source": "Worldometers via covid package",
                "brazil": brazil,
            }
        except ImportError:
            return {"error": "covid not installed"}
        except Exception as e:
            return {"error": str(e)[:100]}


# ─────────────────────────────────────────────────────────────────────
# HOOK 10: QualisDatasetHub — Datasets Qualis A1 (Round 9)
# ─────────────────────────────────────────────────────────────────────


class QualisDatasetHub:
    """Hub de datasets acadêmicos Qualis A1.
    
    Afinidade: datasets(95%) [HuggingFace], openalex(90%)
    """

    @staticmethod
    def list_top_datasets(limit: int = 10) -> list[dict[str, Any]]:
        """Lista datasets populares do HuggingFace Hub."""
        try:
            from datasets import get_dataset_config_names
            # Datasets acadêmicos relevantes
            academic_datasets = [
                "scientific_papers", "pubmed_qa", "multi_news",
                "arxiv_dataset", "sem_scholar", "peer_read",
                "scitldr", "wiki_summary",
            ]
            # Tenta carregar configurações para verificar disponibilidade
            available = []
            for ds in academic_datasets:
                try:
                    configs = get_dataset_config_names(ds)
                    available.append({"name": ds, "configs": len(configs)})
                except Exception:
                    pass
            return available[:limit]
        except ImportError:
            return [{"error": "datasets not installed. pip install datasets"}]
        except Exception as e:
            return [{"error": str(e)[:100]}]

    @staticmethod
    def search_openalex_datasets(query: str, limit: int = 5) -> list[dict[str, Any]]:
        """Busca datasets acadêmicos no OpenAlex."""
        try:
            import httpx
            url = f"https://api.openalex.org/works?search={query}&per_page={limit}"
            resp = httpx.get(url, timeout=30)
            data = resp.json()
            return [
                {
                    "title": w.get("title", ""),
                    "doi": w.get("doi", ""),
                    "cited_by": w.get("cited_by_count", 0),
                    "year": w.get("publication_year", 0),
                    "type": w.get("type", ""),
                    "open_access": w.get("open_access", {}).get("is_oa", False),
                }
                for w in data.get("results", [])
            ]
        except Exception as e:
            logger.error(f"OpenAlex: {e}")
            return []

    @staticmethod
    def get_qualis_a1_sources() -> dict[str, list[str]]:
        """Fontes de datasets Qualis A1 por área."""
        return {
            "computer_science": [
                "arXiv (arxiv.org) — 2.4M+ papers",
                "Semantic Scholar (semanticscholar.org) — 200M+ papers",
                "OpenAlex (openalex.org) — 250M+ works",
                "HuggingFace Datasets — 100K+ datasets",
                "Papers With Code — ML benchmarks",
            ],
            "economics": [
                "FRED (Federal Reserve) — 800K+ series",
                "World Bank WDI — 1400+ indicators",
                "IMF Data — macroeconomic datasets",
                "OECD Data — 40+ databases",
                "BIS Statistics — banking/financial data",
            ],
            "health": [
                "PubMed/NCBI — 36M+ citations",
                "DATASUS (PySUS) — Brazilian public health",
                "WHO GHO — global health observatory",
                "CDC Wonder — US health statistics",
                "MIMIC-III/IV — clinical ICU data",
            ],
            "geography": [
                "IBGE — Brazilian census & geography",
                "Natural Earth — free vector/raster map data",
                "OpenStreetMap — global geographic database",
                "NASA SEDAC — socioeconomic data",
                "GADM — global administrative boundaries",
            ],
        }


# ── Registry (v2.0 — Round 9) ────────────────────────────────────────

HOOKS_REGISTRY = {
    # Round 8
    "seeker_multi_source": SeekerMultiSource,
    "world_bank_analyzer": WorldBankAnalyzer,
    "pdf_processor": PDFProcessor,
    "mcp_scout_bridge": MCPScoutBridge,
    "httpx_client": HTTPXClient,
    # Round 9 — Expansão Multi-Domínio
    "geo_analyzer": GeoAnalyzer,
    "finance_analyzer": FinanceAnalyzer,
    "market_speculator": MarketSpeculator,
    "biomed_analyzer": BioMedAnalyzer,
    "qualis_dataset_hub": QualisDatasetHub,
}
